min_spread_percentage: 0.2
min_profit_percentage: 0.0001
min_profit_amount: 0.0001
use_mainnet: false
order_book_depth: 50
max_stale_duration: 10s
check_interval: 50ms
update_ui_interval: 10ms
quoted_asset: "USDT"
coins:
  - "SOL"
  - "ATOM"
  - "BTC"
  - "APT"
  - "ETH"
trade_fees:
    Hyperliquid: 2
    KuCoin: 2
    Binance: 2
    OKX: 2
    Bybit: 2
    MEXC: 2
