min_spread_percentage: 0.2
min_profit_percentage: 0.15
min_profit_amount: 0.5
use_mainnet: true
order_book_depth: 10
max_stale_duration: 10s
check_interval: 200ms
update_ui_interval: 50ms
coins:
  - "HMSTR"
  - "BOME"
  - "TURBO"
  - "PURR"
  - "DOGE"
trade_fees:
    Hyperliquid: 0.2
    KuCoin: 0.2
    Binance: 0.2
    OKX: 0.2
    Bybit: 0.2
    MEXC: 0.2
