min_spread_percentage: 0.2
min_profit_percentage: 0.15
min_profit_amount: 0.5
use_mainnet: false
order_book_depth: 50
max_stale_duration: 30s
check_interval: 500ms
update_ui_interval: 300ms
quoted_asset: "USDT"
coins:
  - "BTC"
  - "ETH"
  - "SOL"
  - "ATOM"
  - "IOTA"
trade_fees:
    Hyperliquid: 2
    KuCoin: 2
    Binance: 2
    OKX: 2
    Bybit: 2
    MEXC: 2